const actionType = {
    LOAD_DATA_PROGRESS: 'LOAD_DATA_PROGRESS',
    LOAD_DATA_SUCCEED: 'LOAD_DATA_SUCCEED',
    LOAD_DATA_FAIL: 'LOAD_DATA_FAIL',

    SET_CURRENTUSER_PROGRESS: 'SET_CURRENTUSER_PROGRESS',
    SET_CURRENTUSER_SUCCEED: 'SET_CURRENTUSER_SUCCEED',
    SET_CURRENTUSER_FAIL: 'SET_CURRENTUSER_FAIL',

    SET_DATAOBJ_PROGRESS: 'SET_DATAOBJ_PROGRESS',
    SET_DATAOBJ_SUCCEED: 'SET_DATAOBJ_SUCCEED',
    SET_DATAOBJ_FAIL: 'SET_DATAOBJ_FAIL',

    SET_INVENTORY_PROGRESS: 'SET_INVENTORY_PROGRESS',
    SET_INVENTORY_SUCCEED: 'SET_INVENTORY_SUCCEED',
    SET_INVENTORY_FAIL: 'SET_INVENTORY_FAIL',

    PUSH_HISTORY_PROGRESS: 'PUSH_HISTORY_PROGRESS',
    PUSH_HISTORY_SUCCEED: 'PUSH_HISTORY_SUCCEED',
    PUSH_HISTORY_FAIL: 'PUSH_HISTORY_FAIL',


    SYNC_DATA_PROGRESS: 'SYNC_DATA_PROGRESS',
    SYNC_DATA_SUCCEED: 'SYNC_DATA_SUCCEED',
    SYNC_DATA_FAIL: 'SYNC_DATA_FAIL',


    

}

export default actionType;